//Fake users to populate leaderboard
export const fakeUsers = [
    { name: "Manfried", xp: 424, isCurrentUser: false },
    { name: "Amatore", xp: 378, isCurrentUser: false },
    { name: "Notus", xp: 249, isCurrentUser: false },
    { name: "Eugene", xp: 216, isCurrentUser: false },
    { name: "Ellen", xp: 211, isCurrentUser: false },
    { name: "Freddy", xp: 177, isCurrentUser: false },
    { name: "Gudrun", xp: 152, isCurrentUser: false },
    { name: "Gertie", xp: 87, isCurrentUser: false },
    { name: "Isaac", xp: 82, isCurrentUser: false },
    { name: "Jacob", xp: 77, isCurrentUser: false },
    { name: "Pascal", xp: 72, isCurrentUser: false },
    { name: "Kyrie", xp: 71, isCurrentUser: false },
    { name: "Eudokia", xp: 65, isCurrentUser: false },
    { name: "Norm", xp: 62, isCurrentUser: false },
    { name: "Benedikt", xp: 59, isCurrentUser: false },
    { name: "Perry", xp: 52, isCurrentUser: false },
    { name: "Quentin", xp: 51, isCurrentUser: false },
    { name: "Oleg", xp: 45, isCurrentUser: false },
    { name: "Steve", xp: 40, isCurrentUser: false },
    { name: "Conan", xp: 30, isCurrentUser: false },
    { name: "Uma", xp: 20, isCurrentUser: false },
    { name: "Eamon", xp: 10, isCurrentUser: false },
    { name: "Wes", xp: 10, isCurrentUser: false },
    { name: "Xavier", xp: 10, isCurrentUser: false },
    { name: "Yan", xp: 10, isCurrentUser: false },
    { name: "Liz", xp: 10, isCurrentUser: false },
    { name: "Leela", xp: 10, isCurrentUser: false },
    { name: "Petra", xp: 10, isCurrentUser: false },
    { name: "Hideyoshi", xp: 10, isCurrentUser: false },
  ] as const;